// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: api/dropdowns/dropdowns.proto

package dropdowns

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DropDownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropDownRequest) Reset() {
	*x = DropDownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dropdowns_dropdowns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDownRequest) ProtoMessage() {}

func (x *DropDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dropdowns_dropdowns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDownRequest.ProtoReflect.Descriptor instead.
func (*DropDownRequest) Descriptor() ([]byte, []int) {
	return file_api_dropdowns_dropdowns_proto_rawDescGZIP(), []int{0}
}

type ProvinceCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provinces []*ProvinceCityResponse_Provinces `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces,omitempty"`
}

func (x *ProvinceCityResponse) Reset() {
	*x = ProvinceCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dropdowns_dropdowns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvinceCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvinceCityResponse) ProtoMessage() {}

func (x *ProvinceCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dropdowns_dropdowns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvinceCityResponse.ProtoReflect.Descriptor instead.
func (*ProvinceCityResponse) Descriptor() ([]byte, []int) {
	return file_api_dropdowns_dropdowns_proto_rawDescGZIP(), []int{1}
}

func (x *ProvinceCityResponse) GetProvinces() []*ProvinceCityResponse_Provinces {
	if x != nil {
		return x.Provinces
	}
	return nil
}

type ProvinceCityResponse_Provinces struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int64                                    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Province string                                   `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	Cities   []*ProvinceCityResponse_Provinces_Cities `protobuf:"bytes,3,rep,name=cities,proto3" json:"cities,omitempty"`
}

func (x *ProvinceCityResponse_Provinces) Reset() {
	*x = ProvinceCityResponse_Provinces{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dropdowns_dropdowns_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvinceCityResponse_Provinces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvinceCityResponse_Provinces) ProtoMessage() {}

func (x *ProvinceCityResponse_Provinces) ProtoReflect() protoreflect.Message {
	mi := &file_api_dropdowns_dropdowns_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvinceCityResponse_Provinces.ProtoReflect.Descriptor instead.
func (*ProvinceCityResponse_Provinces) Descriptor() ([]byte, []int) {
	return file_api_dropdowns_dropdowns_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ProvinceCityResponse_Provinces) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProvinceCityResponse_Provinces) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ProvinceCityResponse_Provinces) GetCities() []*ProvinceCityResponse_Provinces_Cities {
	if x != nil {
		return x.Cities
	}
	return nil
}

type ProvinceCityResponse_Provinces_Cities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *ProvinceCityResponse_Provinces_Cities) Reset() {
	*x = ProvinceCityResponse_Provinces_Cities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dropdowns_dropdowns_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvinceCityResponse_Provinces_Cities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvinceCityResponse_Provinces_Cities) ProtoMessage() {}

func (x *ProvinceCityResponse_Provinces_Cities) ProtoReflect() protoreflect.Message {
	mi := &file_api_dropdowns_dropdowns_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvinceCityResponse_Provinces_Cities.ProtoReflect.Descriptor instead.
func (*ProvinceCityResponse_Provinces_Cities) Descriptor() ([]byte, []int) {
	return file_api_dropdowns_dropdowns_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ProvinceCityResponse_Provinces_Cities) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProvinceCityResponse_Provinces_Cities) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

var File_api_dropdowns_dropdowns_proto protoreflect.FileDescriptor

var file_api_dropdowns_dropdowns_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x2f,
	0x64, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x77, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x85, 0x02, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x41, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x73, 0x1a, 0xa9, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x42, 0x0a,
	0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x43, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x73, 0x2e, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x1a, 0x2c, 0x0a, 0x06, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x32,
	0x5a, 0x0a, 0x0f, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x47, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x43, 0x69,
	0x74, 0x79, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x43,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x77, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x73, 0x70, 0x61, 0x72, 0x71, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x64, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_dropdowns_dropdowns_proto_rawDescOnce sync.Once
	file_api_dropdowns_dropdowns_proto_rawDescData = file_api_dropdowns_dropdowns_proto_rawDesc
)

func file_api_dropdowns_dropdowns_proto_rawDescGZIP() []byte {
	file_api_dropdowns_dropdowns_proto_rawDescOnce.Do(func() {
		file_api_dropdowns_dropdowns_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_dropdowns_dropdowns_proto_rawDescData)
	})
	return file_api_dropdowns_dropdowns_proto_rawDescData
}

var file_api_dropdowns_dropdowns_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_dropdowns_dropdowns_proto_goTypes = []any{
	(*DropDownRequest)(nil),                       // 0: api.DropDownRequest
	(*ProvinceCityResponse)(nil),                  // 1: api.ProvinceCityResponse
	(*ProvinceCityResponse_Provinces)(nil),        // 2: api.ProvinceCityResponse.Provinces
	(*ProvinceCityResponse_Provinces_Cities)(nil), // 3: api.ProvinceCityResponse.Provinces.Cities
}
var file_api_dropdowns_dropdowns_proto_depIdxs = []int32{
	2, // 0: api.ProvinceCityResponse.provinces:type_name -> api.ProvinceCityResponse.Provinces
	3, // 1: api.ProvinceCityResponse.Provinces.cities:type_name -> api.ProvinceCityResponse.Provinces.Cities
	0, // 2: api.DropDownService.ProvinceCityDropDown:input_type -> api.DropDownRequest
	1, // 3: api.DropDownService.ProvinceCityDropDown:output_type -> api.ProvinceCityResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_dropdowns_dropdowns_proto_init() }
func file_api_dropdowns_dropdowns_proto_init() {
	if File_api_dropdowns_dropdowns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_dropdowns_dropdowns_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DropDownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dropdowns_dropdowns_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProvinceCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dropdowns_dropdowns_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ProvinceCityResponse_Provinces); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dropdowns_dropdowns_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ProvinceCityResponse_Provinces_Cities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_dropdowns_dropdowns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dropdowns_dropdowns_proto_goTypes,
		DependencyIndexes: file_api_dropdowns_dropdowns_proto_depIdxs,
		MessageInfos:      file_api_dropdowns_dropdowns_proto_msgTypes,
	}.Build()
	File_api_dropdowns_dropdowns_proto = out.File
	file_api_dropdowns_dropdowns_proto_rawDesc = nil
	file_api_dropdowns_dropdowns_proto_goTypes = nil
	file_api_dropdowns_dropdowns_proto_depIdxs = nil
}
