// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/dropdowns/dropdowns.proto

package dropdowns

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DropDownService_ProvinceCityDropDown_FullMethodName = "/api.DropDownService/ProvinceCityDropDown"
)

// DropDownServiceClient is the client API for DropDownService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DropDownServiceClient interface {
	ProvinceCityDropDown(ctx context.Context, in *DropDownRequest, opts ...grpc.CallOption) (*ProvinceCityResponse, error)
}

type dropDownServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDropDownServiceClient(cc grpc.ClientConnInterface) DropDownServiceClient {
	return &dropDownServiceClient{cc}
}

func (c *dropDownServiceClient) ProvinceCityDropDown(ctx context.Context, in *DropDownRequest, opts ...grpc.CallOption) (*ProvinceCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvinceCityResponse)
	err := c.cc.Invoke(ctx, DropDownService_ProvinceCityDropDown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DropDownServiceServer is the server API for DropDownService service.
// All implementations must embed UnimplementedDropDownServiceServer
// for forward compatibility.
type DropDownServiceServer interface {
	ProvinceCityDropDown(context.Context, *DropDownRequest) (*ProvinceCityResponse, error)
	mustEmbedUnimplementedDropDownServiceServer()
}

// UnimplementedDropDownServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDropDownServiceServer struct{}

func (UnimplementedDropDownServiceServer) ProvinceCityDropDown(context.Context, *DropDownRequest) (*ProvinceCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvinceCityDropDown not implemented")
}
func (UnimplementedDropDownServiceServer) mustEmbedUnimplementedDropDownServiceServer() {}
func (UnimplementedDropDownServiceServer) testEmbeddedByValue()                         {}

// UnsafeDropDownServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DropDownServiceServer will
// result in compilation errors.
type UnsafeDropDownServiceServer interface {
	mustEmbedUnimplementedDropDownServiceServer()
}

func RegisterDropDownServiceServer(s grpc.ServiceRegistrar, srv DropDownServiceServer) {
	// If the following call pancis, it indicates UnimplementedDropDownServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DropDownService_ServiceDesc, srv)
}

func _DropDownService_ProvinceCityDropDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropDownServiceServer).ProvinceCityDropDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DropDownService_ProvinceCityDropDown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropDownServiceServer).ProvinceCityDropDown(ctx, req.(*DropDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DropDownService_ServiceDesc is the grpc.ServiceDesc for DropDownService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DropDownService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.DropDownService",
	HandlerType: (*DropDownServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProvinceCityDropDown",
			Handler:    _DropDownService_ProvinceCityDropDown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/dropdowns/dropdowns.proto",
}
